### ISSUE TITLE
Estudiar react

### ISSUE THREAD

**Issue by JimenaMV** [JimenaMV/CDMX009-BurgerQueen#8]
## React

- [x] Características
- [x] Componentes
- [x] Ejercicios de componentes
   - [x] Con clases
   - [x] Con funciones
- [x] Props
- [x] Hooks
- [x] Instalación

**Comment by diegovelezg** [comment]
En general, todas las tareas que son "aprender" o "estudiar, podrían (¿deberían?) considerar una "prueba de concepto" o "experimento" que se trate de "implementar" eso que "estudiaste"/"aprendiste"

**Comment by JimenaMV** [comment]
Ok, Diego. Si, justo eso es lo que hemos estado haciendo. Aprendiendo e implementando.
